# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# categories = ["Women’s Clothing", "Men’s Clothing", "Kid’s Clothing", "Appliances", "Mobile Phones", "Tablet PC & Accessories", "Consumer Electronics", "Computers & Networking", "Electrical & Tools", "Bags & Shoes","Toys & Hobbies", "Watches & Jewelry", "Home & Garden", "Health & Beauty", "Outdoors & Sports", "LED Light & Flashlights", "Automobiles & Motorcycle", "Baby & Kids", "Office & School Supplies", "Fashion", "Sports & Outdoors"]
# sub_categories = ["Dresses", "Jeans", "Shoes", "Tops", "Bottoms", "Shorts", "Rompers and Jumpsuits", "Matching Sets", "Activewear", "Accessories", "Lingerie", "Swimwear", "What's Hot"]
# [["Dresses", 1], ["Jeans", 2], ["Shoes", 3], ["Tops", 4], ["Bottoms", 5], ["Shorts", 6], ["Rompers and Jumpsuits", 7], ["Matching Sets", 8], ["Activewear", 9], ["Accessories", 10], ["Lingerie", 11], ["Swimwear", 12], ["What's Hot", 13], ["Plus Size & Curve", 14]]
# ProductType.create(name: "Mini Dresses", sub_category_id: 1)
# ProductType.create(name: "Midi Dresses", sub_category_id: 1)
# ProductType.create(name: "Maxi Dresses", sub_category_id: 1)
# ProductType.create(name: "Special Ocassions", sub_category_id: 1)
# ProductType.create(name: "Little Black Dress", sub_category_id: 1)
# ProductType.create(name: "Little White Dress", sub_category_id: 1)
# ProductType.create(name: "Everyday Dresses", sub_category_id: 1)
# ProductType.create(name: "Sale Dresses", sub_category_id: 1)
# ProductType.create(name: "Business Dresses", sub_category_id: 1)
# ProductType.create(name: "High Waist", sub_category_id: 2)
# ProductType.create(name: "Skinny", sub_category_id: 2)
# ProductType.create(name: "Distressed / Ripped", sub_category_id: 2)
# ProductType.create(name: "Boyfriend / Mom", sub_category_id: 2)
# ProductType.create(name: "Overalls & Flare", sub_category_id: 2)
# ProductType.create(name: "Cropped / Ankle", sub_category_id: 2)
# ProductType.create(name: "Denim Shorts", sub_category_id: 2)
# ProductType.create(name: "Under $20", sub_category_id: 2)
# ProductType.create(name: "Sale Jeans", sub_category_id: 2)
# ProductType.create(name: "Heeled Sandals", sub_category_id: 3)
# ProductType.create(name: "Pumps", sub_category_id: 3)
# ProductType.create(name: "Plateforms", sub_category_id: 3)
# ProductType.create(name: "Wedges", sub_category_id: 3)
# ProductType.create(name: "Flat Sandals", sub_category_id: 3)
# ProductType.create(name: "Flats", sub_category_id: 3)
# ProductType.create(name: "Slides", sub_category_id: 3)
# ProductType.create(name: "Sneakers", sub_category_id: 3)
# ProductType.create(name: "Booties", sub_category_id: 3)
# ProductType.create(name: "Heeled Boots", sub_category_id: 3)
# ProductType.create(name: "Over The Knee Bootss", sub_category_id: 3)
# ProductType.create(name: "Flat Boots", sub_category_id: 3)
# ProductType.create(name: "Must Have Shoes", sub_category_id: 3)
# ProductType.create(name: "Sale Shoes", sub_category_id: 3)
# ProductType.create(name: "Fashion Tops", sub_category_id: 4)
# ProductType.create(name: "Bodysuits", sub_category_id: 4)
# ProductType.create(name: "Going Out Tops", sub_category_id: 4)
# ProductType.create(name: "Shirts & Blouses", sub_category_id: 4)
# ProductType.create(name: "Graphic Tops", sub_category_id: 4)
# ProductType.create(name: "Jackets", sub_category_id: 4)
# ProductType.create(name: "Tees", sub_category_id: 4)
# ProductType.create(name: "Camis & Tanks", sub_category_id: 4)
# ProductType.create(name: "Sweater", sub_category_id: 4)
# ProductType.create(name: "Crop Tops", sub_category_id: 4)
# ProductType.create(name: "Sale Tops", sub_category_id: 4)
# ProductType.create(name: "Shorts", sub_category_id: 5)
# ProductType.create(name: "Pants", sub_category_id: 5)
# ProductType.create(name: "Leggings", sub_category_id: 5)
# ProductType.create(name: "Skirts", sub_category_id: 5)
# ProductType.create(name: "Sale Bottoms", sub_category_id: 5)
# ProductType.create(name: "Rompers", sub_category_id: 7)
# ProductType.create(name: "Jumpsuits", sub_category_id: 7)
# ProductType.create(name: "Sale Rompers & Jumpsuits", sub_category_id: 7)
# ProductType.create(name: "Active Tops", sub_category_id: 9)
# ProductType.create(name: "Active Bottoms", sub_category_id: 9)
# ProductType.create(name: "Active Sets", sub_category_id: 9)
# ProductType.create(name: "Sale Activewear", sub_category_id: 9)
# ProductType.create(name: "Jewelery", sub_category_id: 10)
# ProductType.create(name: "Earrings", sub_category_id: 10)
# ProductType.create(name: "Necklaces", sub_category_id: 10)
# ProductType.create(name: "Body Jewelry", sub_category_id: 10)
# ProductType.create(name: "Bracelets", sub_category_id: 10)
# ProductType.create(name: "Rings", sub_category_id: 10)
# ProductType.create(name: "Sunglasses", sub_category_id: 10)
# ProductType.create(name: "Handbags", sub_category_id: 10)
# ProductType.create(name: "Belts", sub_category_id: 10)
# ProductType.create(name: "Hats & Scarves", sub_category_id: 10)
# ProductType.create(name: "Beauty", sub_category_id: 10)
# ProductType.create(name: "Accessories under $5", sub_category_id: 10)
# ProductType.create(name: "Mens Grooming", sub_category_id: 10)
# ProductType.create(name: "Sale Accessories", sub_category_id: 10)
# ProductType.create(name: "Bras", sub_category_id: 11)
# ProductType.create(name: "Bralettes", sub_category_id: 11)
# ProductType.create(name: "Panties", sub_category_id: 11)
# ProductType.create(name: "Lingerie Accessories", sub_category_id: 11)
# ProductType.create(name: "Teddies", sub_category_id: 11)
# ProductType.create(name: "Sleepwear", sub_category_id: 11)
# ProductType.create(name: "Shapewear", sub_category_id: 11)
# ProductType.create(name: "Lingerie Set", sub_category_id: 11)
# ProductType.create(name: "Sale Lingerie", sub_category_id: 11)
# ProductType.create(name: "One Piece", sub_category_id: 12)
# ProductType.create(name: "Two Piece", sub_category_id: 12)
# ProductType.create(name: "Cover Ups", sub_category_id: 12)
# ProductType.create(name: "Beach Accessories", sub_category_id: 12)
# ProductType.create(name: "Sunglasses", sub_category_id: 12)
# ProductType.create(name: "Flat Sandals", sub_category_id: 12)
# ProductType.create(name: "Sale Swimwear", sub_category_id: 12)
# ProductType.create(name: "Amber Rose's Picks", sub_category_id: 13)
# ProductType.create(name: "Celeb Status", sub_category_id: 13)
# ProductType.create(name: "Miami Heat", sub_category_id: 13)
# ProductType.create(name: "Kylie", sub_category_id: 13)
# ProductType.create(name: "Red, Hot and Blue", sub_category_id: 13)
# ProductType.create(name: "The Denim Shop", sub_category_id: 13)
# ProductType.create(name: "Racer", sub_category_id: 13)
# ProductType.create(name: "Shop Insatagram", sub_category_id: 13)
# ProductType.create(name: "Dresses", sub_category_id: 14)
# ProductType.create(name: "Jeans", sub_category_id: 14)
# ProductType.create(name: "Tops", sub_category_id: 14)
# ProductType.create(name: "Bottoms", sub_category_id: 14)
# ProductType.create(name: "Jackets", sub_category_id: 14)
# ProductType.create(name: "Bodysuits", sub_category_id: 14)
# ProductType.create(name: "Lingerie", sub_category_id: 14)
# ProductType.create(name: "Matching Sets", sub_category_id: 14)
# ProductType.create(name: "Rompers and Jumpsuits", sub_category_id: 14)
# ProductType.create(name: "Sweaters", sub_category_id: 14)
# ProductType.create(name: "Activewear", sub_category_id: 14)
# ProductType.create(name: "Swimwear", sub_category_id: 14)
# ProductType.create(name: "Sale", sub_category_id: 14)